#!/bin/bash
EXITCODE=0;
WATERMARK=$2;
godep go test -cover ./... | while read -r COVEROUTPUT;do 
  echo ${COVEROUTPUT};

  COVERLEVELS=`echo ${COVEROUTPUT} | grep -oh "[0-9]\{1,3\}\.[0-9]\{1,3\}\%"`
  for COVERLEVEL in ${COVERLEVELS};do
      echo ${COVERLEVEL} | tr "%" " ";
      COVERLEVEL=${COVERLEVEL/.*};
      echo "Coverage - ${COVERLEVEL}%";
      echo "Watermark- ${WATERMARK}%";
      if [[ $COVERLEVEL -lt $WATERMARK ]]; then (exit 1); fi
  done
done


